### ISSUE TITLE
Mapping/normalizing user endpoint

### ISSUE THREAD

**Issue by bashilbers** [gigablah/silex-oauth#12]
see UserInforLister.php for:
$token->setUser($userInfo['name']);

"name" exists in some endpoints, but Dropbox for example doesn't return a name; they give "display_name".

Your code will trigger the following exception:

InvalidArgumentException: $user must be an instanceof UserInterface, an object implementing a __toString method, or a primitive string. (uncaught exception)

Any thoughts on mapping the different responses to a single normalized user object?

**Comment by gigablah** [comment]
In v1.0.0 you have the `user_callback` parameter to provide custom logic to extract user information into the token.
