### ISSUE TITLE
Compatibility with Silex 1.3 and symfony/form 2.4+

### ISSUE THREAD

**Issue by rudolfrck** [gigablah/silex-oauth#16]
Hi!

After updating to Silex 1.3 while using 2.4+ version of symfony the following error occurs:

```
Argument 12 passed to Gigablah\Silex\OAuth\Security\Firewall\OAuthAuthenticationListener::__construct() must be an instance of Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfProviderInterface, instance of Symfony\Component\Security\Csrf\CsrfTokenManager given, called in /vagrant/vendor/gigablah/silex-oauth/src/Gigablah/Silex/OAuth/OAuthServiceProvider.php on line 132
```

This is because of this change in Silex 1.3:
https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/FormServiceProvider.php#L109

It looks like Silex 1.3 now returns a `CsrfTokenManager` instead of an object of `CsrfProviderInterface`, but only when using symfony/form 2.4+.

Any suggestions/ideas on how to fix this?
It looks like it might be hard for you to be compatible with the different variations here.

**Comment by bobalazek** [comment]
+1

**Comment by hhsissi** [comment]
+1

**Comment by bobalazek** [comment]
This pull request would solve the problem(-s). Why not merge it?
https://github.com/gigablah/silex-oauth/pull/24

**Comment by alaczi** [comment]
+1 for compatibility

**Comment by gigablah** [comment]
Tag `1.3.0` has been pushed which provides compatibility with Silex 1.3 (<2.0) and Symfony 2.4+.
