### ISSUE TITLE
Extend StabUser

### ISSUE THREAD

**Issue by andreymeretsky** [gigablah/silex-oauth#18]
Hi there! 
I want to store authenticated facebook user info to database but StubUser Class hasn't all the fields that facebook return. How can I extend StubUser to add extra fields such as facebook User id? 
Hope you will help me :)

**Comment by gigablah** [comment]
You shouldn't be using or extending StubUser, you should create your own User class (and your own UserProvider class) to fit your needs. `OAuthInMemoryUserProvider` is the one that instantiates `StubUser` -- you should swap it out in `security.firewalls.default.users` with your own implementation.

**Comment by andreymeretsky** [comment]
Thanks for your answer. I'm new to silex so I don't fully understand where and when I should reimplement classes. Your answer helps me.
