### ISSUE TITLE
Purpose of check_path

### ISSUE THREAD

**Issue by sashless** [gigablah/silex-oauth#19]
Hey,

currently i do try to use this bundle. 

What works is:

* POST to google API
* redirect to `callback_route`

What is not working:

* `check_path` is called without query parameters
*  => results in missing code Exception

I am curious about what is the purpose of the `check_path` route and does it need to do anything ? 
When i get the redirect to `callback_route` the `code` is in the query but then it does a redirect to `check_path` and there is the `code` removed from `httpUtils`. It seems like i need to recreate some response in order to serve the code i get in the `callback_route` ?

**Comment by sashless** [comment]
Okay i think the purpose of `check_path` is the same described here http://symfony.com/doc/current/reference/configuration/security.html ?

**Comment by sashless** [comment]
So i changed the `check_path` accordingly to the docs and now i get an error that the access token is not stored in session. From reading the code it should be set automagically. Any hints what i might missing ?

**Comment by gigablah** [comment]
Did you enable the `SessionServiceProvider`?

**Comment by sashless** [comment]
yea did that. I am using the `SilexSessionProvider` but configured with storage `\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage` and as handler `Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcacheSessionHandler`

In addition i am registering a `AttributeBag` to store the session on `app.session`.

When i do replace it by the default `SilexSessionProvider` it does work. 
Debugging on code shows me that the `OAuthService` is using a different `app.session` than i have registered.

**Comment by sashless** [comment]
alright, i was able to track it down properly. Its related to the `AttributeBag`. I will close the issue now because the main problem is solved from my POV and i will create a new one for the `AttributeBag` thingy.
