### ISSUE TITLE
Storage\SymfonySession is not aware of AttributeBag

### ISSUE THREAD

**Issue by sashless** [gigablah/silex-oauth#20]
from https://github.com/gigablah/silex-oauth/issues/19#issuecomment-94712064

I am registering an `AttributeBag` 

```php
$app['session']->registerBag(
    new \Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag('fooBar')
);
```

This leads to storage/retrieval fails when it comes to use the SymfonySession. To fix it i was in need to use `$this->session->getBag('attributes')->doo()` for every call to the `session` in https://github.com/gigablah/silex-oauth/blob/master/src/Gigablah/Silex/OAuth/Storage/SymfonySession.php#L43-43

IMO the underlying storage should be aware of the attribute bag but unfortunately it is not.

Do i use it wrong or do i need to fix the SymfonySession that way ?

**Comment by gigablah** [comment]
Unfortunately registering a custom `AttributeBag` with the session object does not change the bag that it retrieves values from when you call `Session::get`. The `AttributeBag` must be passed into the session constructor: https://github.com/symfony/HttpFoundation/blob/master/Session/Session.php#L59

What you can do is override `$app['session']` when registering the `SessionServiceProvider` and construct your own `Session` object. The `AttributeBag` should be passed in as the second argument to the constructor.

**Comment by sashless** [comment]
Actually i tryed exactly that and it works. Thank you :+1: But i am curious what it does not work. The `AttributeBag` is registered using the default name `attributes` . I think when i call `registerBag` it should overwrite the default `AttributeBag` registered on the name `attributes` but it does not ?

**Comment by gigablah** [comment]
Yes that's true. You could check whether your previous `registerBag` code somehow happens *after* the session is read. Considering how `Pimple` works you might have triggered early instantiation somewhere. In fact, try using `$app->extend()` on the `session` object.

**Comment by sashless** [comment]
Alright, thanks for your explanation & advice! I am using now `$app->extend()` and it works as expected. 

Thanks for the project :+1:
