### ISSUE TITLE
Please create a new tag

### ISSUE THREAD

**Issue by sashless** [gigablah/silex-oauth#21]
Last tag was 2014, since then there was some progress. Please tag the latest version so i can use it properly for composer :+1:

**Comment by Narno** [comment]
:+1:

**Comment by alaczi** [comment]
I agree. Also it should reach 1.x and start using semver with proper dependency requirements in composer.json

**Comment by gigablah** [comment]
I'll look into this over the weekend.

**Comment by gigablah** [comment]
Tag `1.0.0` has been created, compatible with Silex >=1.0 < 1.3
