### ISSUE TITLE
Question regarding the redirect_uri

### ISSUE THREAD

**Issue by PomepuyN** [gigablah/silex-oauth#27]
I ran into a weird bug and I am not sure what caused it.
The redirect url is not correctly generated anymore (it was working earlier and I failed to find what changed in the meantime).
It has something to do with the ```callback_route``` not using an absolute url.

Error example with a Google login:
> Invalid parameter value for redirect_uri: Missing scheme: /xxx/auth/google/callback

What I found so far is that the url is incorrectly generated here: https://github.com/gigablah/silex-oauth/blob/master/src/OAuthServiceRegistry.php#L110

The ```true``` last parameter is leading to the ```ABSOLUTE_PATH``` constant of the ```UrlGeneratorInterface``` (see https://github.com/symfony/routing/blob/master/Generator/UrlGeneratorInterface.php#L42 )

Of course, if I change the ```true``` parameter to 0 (```ABSOLUTE_URL```) there is no more error.

Is there something I am missing?

**Comment by gigablah** [comment]
Looks like there's a BC break with Symfony 3.0 (before this, `true` would be mapped to `ABSOLUTE_URL`). I'll see if I can push out a new version soon that's pegged to the 3.0 libraries.

**Comment by enyosolutions** [comment]
+1 here, it still trying to figure what component i should delete to get back to when it was working

**Comment by gigablah** [comment]
Alright, I've updated the master and added new tags. It should work now if you've using `1.0.1`, `1.3.1` or 2.0@dev/master.
