### ISSUE TITLE
Generated urls are relatives since symfony/routing 3.0

### ISSUE THREAD

**Issue by lebris** [gigablah/silex-oauth#28]
[In the OAuthServiceRegistry](https://github.com/gigablah/silex-oauth/blob/master/src/OAuthServiceRegistry.php#L112) `true` as value for the referenceType parameter to the url generator method `generate()` which is not supported in version 3.0 of symfony/routing (cf [UrlGeneratorInterface for symfony 3.0](https://github.com/symfony/routing/blob/3.0/Generator/UrlGeneratorInterface.php#L74))

You should add this in the `composer.json`
```json
"symfony/routing": "~2.4,<3.0"
```

Btw, the readme tell us to add symfony/form, symfony/security dependencies to our composer.json, but  why ? 
the package dependencies should be in the gigablah/silex-oauth `composer.json` itself.

**Comment by gigablah** [comment]
The presence of symfony/form and symfony/security in the README is merely implementation details for an example Silex app. It's possible to use this package without symfony/form for example, if you don't need CSRF tokens. I suppose I'll add a comment.

**Comment by gigablah** [comment]
Alright, I've updated the master and added new tags. It should work now if you're using `1.0.1`, `1.3.1` or 2.0@dev/master. No need to change your `symfony/routing` version.
