### ISSUE TITLE
Adding Tumblr?

### ISSUE THREAD

**Issue by toddmbloom** [gigablah/silex-oauth#3]
I can't seem to add a Tumblr option. I put in the key and secret and get redirected to the authentication page but I get an error on /auth/tumblr/check for:

InvalidArgumentException: $user must be an instanceof UserInterface, an object implementing a __toString method, or a primitive string.

**Comment by enyosolutions** [comment]
I'm having the same issue with vkontakte. Where in your code is the listener located ?
